baseURL = "https://foistories.netlify.app"
languageCode = "en-gb"
title = "FOIStories"
theme = "PaperMod"

[taxonomies]
  tag          = "tags"
  topic        = "topics"
  authority    = "authorities"
  jurisdiction = "jurisdictions"
  exemption    = "exemptions"

[params]
  mainSections = ["stories"]
  defaultTheme = "light"
  disableThemeToggle = true

  [params.assets]
    customCSS = ["css/foistories.css"]
